// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/analizer/Lexer.flex

package compiler;
import compilerTools.Token;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\0\1\7\1\10\1\0\1\11\1\0\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\0\1\20\1\21"+
    "\11\22\1\0\1\23\1\24\1\25\1\26\2\0\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\2\27\1\35\3\27"+
    "\1\36\2\27\1\37\1\27\1\40\1\41\1\42\2\27"+
    "\1\43\3\27\1\44\1\0\1\45\1\0\1\27\1\0"+
    "\1\46\1\27\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\27\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\1\65\1\66\1\67\1\70\4\27\1\71\1\72"+
    "\1\73\1\74\7\0\1\3\73\0\1\27\7\0\1\27"+
    "\3\0\1\27\3\0\1\27\1\0\1\27\6\0\1\27"+
    "\1\0\1\27\4\0\1\27\7\0\1\27\3\0\1\27"+
    "\3\0\1\27\1\0\1\27\6\0\1\27\1\0\1\27"+
    "\u012b\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\1\0\1\2\1\3\2\1\1\4"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\1\1\15\1\16\1\17\1\20\15\1\1\21\1\22"+
    "\15\1\1\23\1\4\1\24\1\25\2\0\1\26\1\27"+
    "\1\30\2\0\1\31\2\0\1\14\1\32\1\33\1\34"+
    "\1\0\1\35\4\0\1\36\34\0\1\37\2\0\1\40"+
    "\1\0\1\41\1\17\36\0\1\42\31\0\1\37\6\0"+
    "\1\2\4\0\1\43\2\0\1\44\5\0\1\45\2\0"+
    "\1\2\11\0\1\46\1\0\1\47\1\0\1\2\4\0"+
    "\1\50\1\2\15\0\1\51\3\0\1\52\1\0\1\53"+
    "\2\0\1\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[235];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\172\0\75\0\172\0\267\0\364\0\u0131"+
    "\0\u016e\0\u01ab\0\75\0\75\0\75\0\u01e8\0\75\0\u0225"+
    "\0\u0262\0\u029f\0\u02dc\0\75\0\u0319\0\u0356\0\u0393\0\u03d0"+
    "\0\u040d\0\u044a\0\u0487\0\u04c4\0\u0501\0\u053e\0\u057b\0\u05b8"+
    "\0\u05f5\0\u0632\0\u066f\0\u06ac\0\75\0\75\0\u06e9\0\u0726"+
    "\0\u0763\0\u07a0\0\u07dd\0\u081a\0\u0857\0\u0894\0\u08d1\0\u090e"+
    "\0\u094b\0\u0988\0\u09c5\0\75\0\u0a02\0\75\0\75\0\u0a3f"+
    "\0\u0a7c\0\75\0\75\0\u0ab9\0\u0af6\0\u0b33\0\75\0\u0b70"+
    "\0\u02dc\0\75\0\75\0\75\0\75\0\u03d0\0\75\0\u0bad"+
    "\0\u0bea\0\u0c27\0\u0c64\0\u03d0\0\u0ca1\0\u04c4\0\u0cde\0\u0d1b"+
    "\0\u0d58\0\u0d95\0\u0dd2\0\u0e0f\0\u0e4c\0\u0e89\0\u0ec6\0\u0f03"+
    "\0\u0f40\0\u0f7d\0\u0fba\0\u0ff7\0\u1034\0\u1071\0\u10ae\0\u10eb"+
    "\0\u1128\0\u1165\0\u11a2\0\u11df\0\u07a0\0\u121c\0\u1259\0\u1296"+
    "\0\u12d3\0\u1310\0\u134d\0\75\0\u138a\0\75\0\75\0\u13c7"+
    "\0\u1404\0\u1441\0\u147e\0\u14bb\0\u14f8\0\u1535\0\u1572\0\u15af"+
    "\0\u15ec\0\u1629\0\u1666\0\u16a3\0\u16e0\0\u171d\0\u175a\0\u1797"+
    "\0\u17d4\0\u1811\0\u184e\0\u188b\0\u18c8\0\u1905\0\u1942\0\u197f"+
    "\0\u19bc\0\u19f9\0\u1a36\0\u1a73\0\u1ab0\0\u03d0\0\u1aed\0\u1b2a"+
    "\0\u1b67\0\u1ba4\0\u1be1\0\u1c1e\0\u1c5b\0\u1c98\0\u1cd5\0\u1d12"+
    "\0\u1d4f\0\u1d8c\0\u1dc9\0\u1e06\0\u1e43\0\u1e80\0\u1ebd\0\u1efa"+
    "\0\u1f37\0\u1f74\0\u1fb1\0\u1fee\0\u202b\0\u2068\0\u20a5\0\u03d0"+
    "\0\u20e2\0\u211f\0\u215c\0\u2199\0\u21d6\0\u2213\0\u2250\0\u228d"+
    "\0\u22ca\0\u2307\0\u2344\0\u03d0\0\u2381\0\u23be\0\u03d0\0\u23fb"+
    "\0\u2438\0\u2475\0\u24b2\0\u24ef\0\u03d0\0\u252c\0\u2569\0\u13c7"+
    "\0\u2250\0\u25a6\0\u25e3\0\u2620\0\u265d\0\u269a\0\u26d7\0\u2714"+
    "\0\u2751\0\u03d0\0\u278e\0\75\0\u27cb\0\172\0\u2808\0\u2845"+
    "\0\u2882\0\u28bf\0\u28fc\0\u2199\0\u2939\0\u2976\0\u29b3\0\u29f0"+
    "\0\u2a2d\0\u2a6a\0\u2aa7\0\u2ae4\0\u2b21\0\u2b5e\0\u2b9b\0\u2bd8"+
    "\0\u2c15\0\u03d0\0\u2c52\0\u2c8f\0\u2ccc\0\u03d0\0\u2d09\0\u03d0"+
    "\0\u2d46\0\u2d83\0\u03d0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[235];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\0\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\2\30\1\54\1\30\1\55\1\30"+
    "\1\56\1\57\1\60\1\30\1\61\1\62\1\63\2\30"+
    "\1\64\1\65\1\66\120\0\1\4\53\0\1\5\117\0"+
    "\1\67\70\0\2\70\4\0\15\70\2\0\24\70\1\0"+
    "\1\70\30\0\15\71\2\0\24\71\14\0\1\72\100\0"+
    "\1\73\76\0\1\74\71\0\1\75\3\0\1\76\75\0"+
    "\1\77\1\100\73\0\2\101\1\102\76\0\1\103\74\0"+
    "\1\104\74\0\1\105\70\0\2\106\1\107\3\0\15\106"+
    "\2\0\24\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\14\106\1\110\2\106\1\111\4\106\24\0\2\106\1\107"+
    "\3\0\15\106\2\0\6\106\1\112\5\106\1\113\7\106"+
    "\24\0\2\106\1\107\3\0\15\106\2\0\14\106\1\114"+
    "\7\106\24\0\2\106\1\107\3\0\15\106\2\0\11\106"+
    "\1\115\12\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\1\116\10\106\1\117\2\106\1\120\5\106\1\121\1\106"+
    "\24\0\2\106\1\107\3\0\15\106\2\0\4\106\1\114"+
    "\6\106\1\122\10\106\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\1\123\23\106\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\17\106\1\124\4\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\3\106\1\125\20\106\24\0\2\106\1\107"+
    "\3\0\15\106\2\0\1\106\1\126\17\106\1\127\2\106"+
    "\24\0\2\106\1\107\3\0\15\106\2\0\17\106\1\130"+
    "\4\106\24\0\2\106\1\107\3\0\15\106\2\0\6\106"+
    "\1\131\15\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\2\106\1\132\16\106\1\133\2\106\24\0\2\106\1\107"+
    "\3\0\15\106\2\0\14\106\1\134\7\106\24\0\2\106"+
    "\1\107\3\0\15\106\2\0\3\106\1\135\20\106\24\0"+
    "\2\106\1\107\3\0\15\106\2\0\20\106\1\136\3\106"+
    "\24\0\2\106\1\107\3\0\15\106\2\0\7\106\1\137"+
    "\14\106\24\0\2\106\1\107\3\0\15\106\2\0\13\106"+
    "\1\140\7\106\1\141\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\1\142\23\106\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\14\106\1\143\5\106\1\144\1\106\24\0\2\106"+
    "\1\107\3\0\15\106\2\0\3\106\1\145\20\106\24\0"+
    "\2\106\1\107\3\0\15\106\2\0\7\106\1\146\4\106"+
    "\1\147\7\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\3\106\1\150\20\106\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\7\106\1\151\12\106\1\152\1\106\24\0\2\106"+
    "\1\107\3\0\15\106\2\0\14\106\1\153\7\106\76\0"+
    "\1\154\22\0\2\155\4\0\15\155\2\0\24\155\1\0"+
    "\1\155\22\0\2\71\1\156\3\0\15\71\2\0\24\71"+
    "\31\0\1\157\46\0\14\160\1\161\60\160\2\162\1\5"+
    "\2\162\1\163\67\162\21\0\2\100\1\77\72\0\2\106"+
    "\1\107\3\0\15\106\2\0\14\106\1\164\7\106\24\0"+
    "\2\106\1\107\3\0\15\106\2\0\3\106\1\165\20\106"+
    "\24\0\2\106\1\107\3\0\15\106\2\0\1\120\23\106"+
    "\24\0\2\106\1\107\3\0\15\106\2\0\13\106\1\166"+
    "\10\106\24\0\2\106\1\107\3\0\15\106\2\0\20\106"+
    "\1\167\3\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\14\106\1\170\7\106\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\17\106\1\114\4\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\13\106\1\171\10\106\24\0\2\106\1\107"+
    "\3\0\15\106\2\0\21\106\1\114\2\106\24\0\2\106"+
    "\1\107\3\0\15\106\2\0\7\106\1\172\14\106\24\0"+
    "\2\106\1\107\3\0\15\106\2\0\7\106\1\173\14\106"+
    "\24\0\2\106\1\107\3\0\15\106\2\0\21\106\1\174"+
    "\2\106\24\0\2\106\1\107\3\0\15\106\2\0\1\172"+
    "\23\106\24\0\2\106\1\107\3\0\15\106\2\0\17\106"+
    "\1\175\4\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\22\106\1\167\1\106\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\7\106\1\176\14\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\3\106\1\177\20\106\24\0\2\106\1\107"+
    "\3\0\15\106\2\0\17\106\1\200\4\106\24\0\2\106"+
    "\1\107\3\0\15\106\2\0\11\106\1\201\12\106\24\0"+
    "\2\106\1\107\3\0\15\106\2\0\17\106\1\202\1\106"+
    "\1\203\2\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\21\106\1\204\2\106\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\13\106\1\205\10\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\21\106\1\206\2\106\24\0\2\106\1\107"+
    "\3\0\15\106\2\0\16\106\1\207\5\106\24\0\2\106"+
    "\1\107\3\0\15\106\2\0\13\106\1\210\10\106\24\0"+
    "\2\106\1\107\3\0\15\106\2\0\17\106\1\136\4\106"+
    "\24\0\2\106\1\107\3\0\15\106\2\0\12\106\1\211"+
    "\11\106\24\0\2\106\1\107\3\0\15\106\2\0\13\106"+
    "\1\212\10\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\13\106\1\213\10\106\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\15\106\1\214\6\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\13\106\1\215\10\106\24\0\2\106\1\107"+
    "\3\0\15\106\2\0\17\106\1\216\4\106\24\0\2\106"+
    "\1\107\3\0\15\106\2\0\12\106\1\217\11\106\24\0"+
    "\2\220\4\0\15\220\2\0\24\220\1\0\1\220\1\0"+
    "\14\160\1\221\60\160\14\222\1\223\3\222\1\224\2\222"+
    "\1\225\51\222\23\0\1\76\53\0\1\226\20\0\1\4"+
    "\72\0\2\106\1\107\3\0\15\106\2\0\11\106\1\114"+
    "\12\106\24\0\2\106\1\107\3\0\15\106\2\0\1\227"+
    "\23\106\24\0\2\106\1\107\3\0\15\106\2\0\21\106"+
    "\1\230\2\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\3\106\1\114\20\106\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\1\122\23\106\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\1\106\1\114\22\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\13\106\1\114\10\106\24\0\2\106\1\107"+
    "\3\0\15\106\2\0\13\106\1\122\10\106\24\0\2\106"+
    "\1\107\3\0\15\106\2\0\22\106\1\231\1\106\24\0"+
    "\2\106\1\107\3\0\15\106\2\0\7\106\1\232\14\106"+
    "\24\0\2\106\1\107\3\0\15\106\2\0\11\106\1\167"+
    "\12\106\24\0\2\106\1\107\3\0\15\106\2\0\11\106"+
    "\1\233\12\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\1\234\23\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\14\106\1\235\7\106\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\3\106\1\236\20\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\3\106\1\237\20\106\24\0\2\106\1\107"+
    "\3\0\15\106\2\0\3\106\1\216\20\106\24\0\2\106"+
    "\1\107\3\0\15\106\2\0\1\240\23\106\24\0\2\106"+
    "\1\107\3\0\15\106\2\0\3\106\1\241\20\106\24\0"+
    "\2\106\1\107\3\0\15\106\2\0\22\106\1\242\1\106"+
    "\24\0\2\106\1\107\3\0\15\106\2\0\23\106\1\243"+
    "\24\0\2\106\1\107\3\0\15\106\2\0\3\106\1\244"+
    "\20\106\24\0\2\106\1\107\3\0\15\106\2\0\21\106"+
    "\1\245\2\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\3\106\1\246\20\106\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\3\106\1\247\20\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\14\106\1\250\7\106\24\0\2\106\1\107"+
    "\3\0\15\106\2\0\1\246\23\106\24\0\2\251\4\0"+
    "\15\251\2\0\24\251\1\0\1\251\1\0\14\160\1\252"+
    "\3\160\1\5\54\160\14\222\1\253\6\222\1\225\65\222"+
    "\1\223\3\222\1\254\54\222\14\255\1\256\6\255\1\257"+
    "\51\255\14\222\1\260\6\222\1\225\51\222\23\0\1\5"+
    "\72\0\2\106\1\107\3\0\15\106\2\0\10\106\1\114"+
    "\13\106\24\0\2\106\1\107\3\0\15\106\2\0\7\106"+
    "\1\261\14\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\17\106\1\172\4\106\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\13\106\1\262\10\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\1\263\23\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\20\106\1\216\3\106\24\0\2\106\1\107"+
    "\3\0\15\106\2\0\17\106\1\264\4\106\24\0\2\106"+
    "\1\107\3\0\15\106\2\0\1\106\1\265\22\106\24\0"+
    "\2\106\1\107\3\0\15\106\2\0\13\106\1\266\10\106"+
    "\24\0\2\106\1\107\3\0\15\106\2\0\11\106\1\267"+
    "\12\106\24\0\2\106\1\107\3\0\15\106\2\0\17\106"+
    "\1\270\4\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\7\106\1\271\14\106\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\1\272\23\106\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\17\106\1\273\4\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\1\274\23\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\17\106\1\275\4\106\24\0\2\106\1\107"+
    "\3\0\15\106\2\0\21\106\1\276\2\106\24\0\2\277"+
    "\4\0\15\277\2\0\24\277\1\0\1\277\1\0\14\160"+
    "\1\252\3\160\1\254\54\160\14\222\1\223\3\222\1\5"+
    "\54\222\14\160\1\221\6\160\1\300\51\160\14\255\1\256"+
    "\6\255\1\301\65\255\1\256\3\255\1\0\70\255\1\302"+
    "\6\255\1\301\51\255\14\222\1\303\3\222\1\304\54\222"+
    "\21\0\2\106\1\107\3\0\15\106\2\0\13\106\1\130"+
    "\10\106\24\0\2\106\1\107\3\0\15\106\2\0\5\106"+
    "\1\114\16\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\13\106\1\136\10\106\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\6\106\1\305\15\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\3\106\1\306\20\106\24\0\2\106\1\107"+
    "\3\0\15\106\2\0\17\106\1\307\4\106\24\0\2\106"+
    "\1\107\3\0\15\106\2\0\3\106\1\310\20\106\24\0"+
    "\2\106\1\107\3\0\15\106\2\0\17\106\1\311\4\106"+
    "\24\0\2\106\1\107\3\0\15\106\2\0\14\106\1\264"+
    "\7\106\24\0\2\106\1\107\3\0\15\106\2\0\17\106"+
    "\1\312\4\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\7\106\1\313\14\106\24\0\2\314\4\0\15\314\2\0"+
    "\24\314\1\0\1\314\1\0\14\255\1\302\3\255\1\226"+
    "\54\255\14\222\1\303\3\222\1\315\54\222\23\0\1\316"+
    "\72\0\2\106\1\107\3\0\15\106\2\0\1\216\23\106"+
    "\24\0\2\106\1\107\3\0\15\106\2\0\17\106\1\317"+
    "\4\106\24\0\2\106\1\107\3\0\15\106\2\0\22\106"+
    "\1\320\1\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\17\106\1\321\4\106\24\0\2\106\1\107\3\0\7\106"+
    "\1\322\5\106\2\0\24\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\17\106\1\323\4\106\3\0\14\160\1\221"+
    "\6\160\1\324\51\160\21\0\2\106\1\107\3\0\10\106"+
    "\1\325\4\106\2\0\24\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\12\106\1\326\11\106\24\0\2\106\1\107"+
    "\3\0\15\106\2\0\2\106\1\305\21\106\24\0\2\106"+
    "\1\107\3\0\15\106\2\0\14\106\1\327\7\106\24\0"+
    "\2\106\1\107\3\0\7\106\1\330\5\106\2\0\24\106"+
    "\24\0\2\106\1\107\3\0\15\106\2\0\7\106\1\331"+
    "\14\106\24\0\2\106\1\107\3\0\15\106\2\0\15\106"+
    "\1\332\6\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\13\106\1\333\10\106\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\7\106\1\334\14\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\13\106\1\335\10\106\24\0\2\106\1\107"+
    "\3\0\15\106\2\0\7\106\1\336\14\106\24\0\2\106"+
    "\1\107\3\0\15\106\2\0\3\106\1\337\20\106\24\0"+
    "\2\106\1\107\3\0\15\106\2\0\3\106\1\340\20\106"+
    "\24\0\2\106\1\107\3\0\15\106\2\0\21\106\1\341"+
    "\2\106\24\0\2\106\1\107\3\0\15\106\2\0\17\106"+
    "\1\342\4\106\24\0\2\106\1\107\3\0\15\106\2\0"+
    "\2\106\1\343\21\106\24\0\2\106\1\107\3\0\15\106"+
    "\2\0\13\106\1\344\10\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\1\345\23\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\1\346\23\106\24\0\2\106\1\107\3\0"+
    "\15\106\2\0\21\106\1\347\2\106\24\0\2\106\1\107"+
    "\3\0\15\106\2\0\17\106\1\350\4\106\24\0\2\106"+
    "\1\107\3\0\15\106\2\0\17\106\1\351\4\106\24\0"+
    "\2\106\1\107\3\0\15\106\2\0\1\352\23\106\24\0"+
    "\2\106\1\107\3\0\15\106\2\0\20\106\1\353\3\106"+
    "\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11712];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\1\0\5\1\3\11\1\1"+
    "\1\11\4\1\1\11\20\1\2\11\15\1\1\11\1\1"+
    "\2\11\2\0\2\11\1\1\2\0\1\11\2\0\4\11"+
    "\1\0\1\11\4\0\1\1\34\0\1\1\2\0\1\11"+
    "\1\0\2\11\36\0\1\1\31\0\1\1\6\0\1\1"+
    "\4\0\1\1\2\0\1\1\5\0\1\1\2\0\1\1"+
    "\11\0\1\1\1\0\1\11\1\0\1\1\4\0\2\1"+
    "\15\0\1\1\3\0\1\1\1\0\1\1\2\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[235];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token token(String lexeme, String lexicalComp, int line, int column) {
        return new Token(lexeme, lexicalComp, line+1, column+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(yytext(), "ERROR", yyline, yycolumn);
            }
            // fall through
          case 44: break;
          case 2:
            { /* Ignorar */
            }
            // fall through
          case 45: break;
          case 3:
            { return token(yytext(), "NOT", yyline, yycolumn);
            }
            // fall through
          case 46: break;
          case 4:
            { return token(yytext(), "OPERADOR_LOGICO", yyline, yycolumn);
            }
            // fall through
          case 47: break;
          case 5:
            { return token(yytext(), "PARENTESIS_IZQ", yyline, yycolumn);
            }
            // fall through
          case 48: break;
          case 6:
            { return token(yytext(), "PARENTESIS_DER", yyline, yycolumn);
            }
            // fall through
          case 49: break;
          case 7:
            { return token(yytext(), "MULTIPLICACION", yyline, yycolumn);
            }
            // fall through
          case 50: break;
          case 8:
            { return token(yytext(), "SUMA", yyline, yycolumn);
            }
            // fall through
          case 51: break;
          case 9:
            { return token(yytext(), "COMA", yyline, yycolumn);
            }
            // fall through
          case 52: break;
          case 10:
            { return token(yytext(), "RESTA", yyline, yycolumn);
            }
            // fall through
          case 53: break;
          case 11:
            { return token(yytext(), "DIVISION", yyline, yycolumn);
            }
            // fall through
          case 54: break;
          case 12:
            { return token(yytext(), "NUMERO", yyline, yycolumn);
            }
            // fall through
          case 55: break;
          case 13:
            { return token(yytext(), "PUNTO_Y_COMA", yyline, yycolumn);
            }
            // fall through
          case 56: break;
          case 14:
            { return token(yytext(), "MENOR_QUE", yyline, yycolumn);
            }
            // fall through
          case 57: break;
          case 15:
            { return token(yytext(), "ASIGNACION", yyline, yycolumn);
            }
            // fall through
          case 58: break;
          case 16:
            { return token(yytext(), "MAYOR_QUE", yyline, yycolumn);
            }
            // fall through
          case 59: break;
          case 17:
            { return token(yytext(), "CORCHETE_IZQ", yyline, yycolumn);
            }
            // fall through
          case 60: break;
          case 18:
            { return token(yytext(), "CORCHETE_DER", yyline, yycolumn);
            }
            // fall through
          case 61: break;
          case 19:
            { return token(yytext(), "LLAVE_IZQ", yyline, yycolumn);
            }
            // fall through
          case 62: break;
          case 20:
            { return token(yytext(), "LLAVE_DER", yyline, yycolumn);
            }
            // fall through
          case 63: break;
          case 21:
            { return token(yytext(), "DIFERENTE_QUE", yyline, yycolumn);
            }
            // fall through
          case 64: break;
          case 22:
            { return token(yytext(), "AND", yyline, yycolumn);
            }
            // fall through
          case 65: break;
          case 23:
            { return token(yytext(), "INCREMENTO", yyline, yycolumn);
            }
            // fall through
          case 66: break;
          case 24:
            { return token(yytext(), "DECREMENTO", yyline, yycolumn);
            }
            // fall through
          case 67: break;
          case 25:
            { return token(yytext(), "ERROR_NUMERO", yyline, yycolumn);
            }
            // fall through
          case 68: break;
          case 26:
            { return token(yytext(), "MENOR_IGUAL_QUE", yyline, yycolumn);
            }
            // fall through
          case 69: break;
          case 27:
            { return token(yytext(), "IGUAL_QUE", yyline, yycolumn);
            }
            // fall through
          case 70: break;
          case 28:
            { return token(yytext(), "MAYOR_IGUAL_QUE", yyline, yycolumn);
            }
            // fall through
          case 71: break;
          case 29:
            { return token(yytext(), "ERROR_IDENTIFICADOR", yyline, yycolumn);
            }
            // fall through
          case 72: break;
          case 30:
            { return token(yytext(), "PALABRA_RESERVADA", yyline, yycolumn);
            }
            // fall through
          case 73: break;
          case 31:
            { return token(yytext(), "ESTRUCTURA_SI", yyline, yycolumn);
            }
            // fall through
          case 74: break;
          case 32:
            { return token(yytext(), "OR", yyline, yycolumn);
            }
            // fall through
          case 75: break;
          case 33:
            { return token(yytext(), "IDENTIFICADOR", yyline, yycolumn);
            }
            // fall through
          case 76: break;
          case 34:
            { return token(yytext(), "MOVIMIENTO", yyline, yycolumn);
            }
            // fall through
          case 77: break;
          case 35:
            { return token(yytext(), "TIPO_DE_DATO", yyline, yycolumn);
            }
            // fall through
          case 78: break;
          case 36:
            { return token(yytext(), "FINAL", yyline, yycolumn);
            }
            // fall through
          case 79: break;
          case 37:
            { return token(yytext(), "TOMAR", yyline, yycolumn);
            }
            // fall through
          case 80: break;
          case 38:
            { return token(yytext(), "PINTAR", yyline, yycolumn);
            }
            // fall through
          case 81: break;
          case 39:
            { return token(yytext(), "COLOR", yyline, yycolumn);
            }
            // fall through
          case 82: break;
          case 40:
            { return token(yytext(), "REPETIR", yyline, yycolumn);
            }
            // fall through
          case 83: break;
          case 41:
            { return token(yytext(), "DETENER_REPETIR", yyline, yycolumn);
            }
            // fall through
          case 84: break;
          case 42:
            { return token(yytext(), "LANZAR_MONEDA", yyline, yycolumn);
            }
            // fall through
          case 85: break;
          case 43:
            { return token(yytext(), "DETENER_PINTAR", yyline, yycolumn);
            }
            // fall through
          case 86: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
